# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest https://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary
  - C:\Program Files (x86)\Pandoc\

# Adapt as necessary starting from here
environment:
  matrix:
    - R_VERSION: stable
      R_ARCH: x64
      GCC_PATH: mingw_64
      CRAN: https://cran.rstudio.com

build_script:
  - travis-tool.sh install_deps
  - bash.exe ./pkgdown/install-pkgs.sh

before_test:
  - ps: >-
      if (-Not (Test-Path "C:\Program Files (x86)\Pandoc\")) {
        cinst pandoc
      }
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v

#test_script:
#  - travis-tool.sh run_tests

on_finish:
  - bash.exe ./pkgdown/build-dll.sh
  - Rscript.exe --verbose ./pkgdown/build-site.R
  - bash.exe ./pkgdown/deploy.sh

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
