language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # CMake
    - CMAKE_URL=https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz
    # OpenCL
    - OPENCL_LIB=default
    - OPENCL_HEADERS_VER="22"
    # Khronos OpenCL ICD
    - OPENCL_REGISTRY=https://www.khronos.org/registry/cl
    - OPENCL_ROOT=${DEPS_DIR}/opencl
    # POCL
    - POCL_BRANCH=release_1_0 # branch/tag
    - POCL_LLVM_VERSION=5.0.1
    - POCL_ROOT=${OPENCL_ROOT}/pocl-${POCL_BRANCH}/
    - POCL_LLVM_CONFIG=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/llvm-config
    - POCL_CXX_COMPILER=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/clang++
    - POCL_C_COMPILER=${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}/bin/clang
    - POCL_OPENCL_LIB=${POCL_ROOT}/lib/libOpenCL.so
    # AMD APP SDK
    - AMDAPPSDKROOT=${OPENCL_ROOT}/AMDAPPSDK
    # Global build options and C++ flags
    - GCC_VERSION=4.8
    - CMAKE_OPTIONS="-DBOOST_COMPUTE_BUILD_TESTS=ON -DBOOST_COMPUTE_BUILD_EXAMPLES=ON -DBOOST_COMPUTE_BUILD_BENCHMARKS=ON -DBOOST_COMPUTE_USE_OFFLINE_CACHE=ON -DBOOST_COMPUTE_HAVE_OPENCV=ON -DBOOST_COMPUTE_THREAD_SAFE=ON"
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow -DCI_BUILD"
    # Boost
    - BOOST_VERSION=default
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  include:
    ############################################################################
    # POCL builds (OpenCL 1.0, 1.1, 1.2)
    ############################################################################

    # Trusty, OpenCL 1.0
    # CLANG
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages: &trusty_pocl_packages
            - g++-4.8
            # POCL
            - libltdl-dev
            - libhwloc-dev
            - pkg-config
            - libedit-dev
            # Boost
            - libboost-chrono1.55-dev
            - libboost-date-time1.55-dev
            - libboost-test1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-timer1.55-dev
            - libboost-program-options1.55-dev
            - libboost-thread1.55-dev
            # Misc
            - python-yaml
            - lcov
            - libopencv-dev
          sources: &trusty_pocl_sources
            - ubuntu-toolchain-r-test
      env:
       - OPENCL_LIB=pocl
       - OPENCL_HEADERS_VER="22"
       - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=100"
       - ENV_CMAKE_OPTIONS="-DOpenCL_LIBRARY=${POCL_OPENCL_LIB} -DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"
    # GCC
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          packages: *trusty_pocl_packages
          sources: *trusty_pocl_sources
      env:
       - OPENCL_LIB=pocl
       - OPENCL_HEADERS_VER="22"
       - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=100"
       - ENV_CMAKE_OPTIONS="-DOpenCL_LIBRARY=${POCL_OPENCL_LIB} -DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"
    # Trusty, OpenCL 1.1
    # CLANG
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages: *trusty_pocl_packages
          sources: *trusty_pocl_sources
      env:
       - OPENCL_LIB=pocl
       - OPENCL_HEADERS_VER="22"
       - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=101"
       - ENV_CMAKE_OPTIONS="-DOpenCL_LIBRARY=${POCL_OPENCL_LIB} -DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"
    # GCC
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          packages: *trusty_pocl_packages
          sources: *trusty_pocl_sources
      env:
       - OPENCL_LIB=pocl
       - OPENCL_HEADERS_VER="22"
       - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=101"
       - ENV_CMAKE_OPTIONS="-DOpenCL_LIBRARY=${POCL_OPENCL_LIB} -DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"
    # Trusty, OpenCL 1.2
    # CLANG
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages: *trusty_pocl_packages
          sources: *trusty_pocl_sources
      env:
       - OPENCL_LIB=pocl
       - OPENCL_HEADERS_VER="22"
       - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=102"
       - ENV_CMAKE_OPTIONS="-DOpenCL_LIBRARY=${POCL_OPENCL_LIB} -DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"
    # GCC
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          packages: *trusty_pocl_packages
          sources: *trusty_pocl_sources
      env:
       - OPENCL_LIB=pocl
       - OPENCL_HEADERS_VER="22"
       - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=102"
       - ENV_CMAKE_OPTIONS="-DOpenCL_LIBRARY=${POCL_OPENCL_LIB} -DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"

    ############################################################################
    # AMD APP SDK builds (v2.9.1 -> OpenCL 1.2, v3.0 -> OpenCL 2.0)
    ############################################################################

    # Trusty, AMD APP SDK v2.9.1, OpenCL 1.2
    # CLANG
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages: &trusty_amdappsdk_packages
            - g++-4.8
            # Boost
            - libboost-chrono1.55-dev
            - libboost-date-time1.55-dev
            - libboost-test1.55-dev
            - libboost-system1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-timer1.55-dev
            - libboost-program-options1.55-dev
            - libboost-thread1.55-dev
            # Misc
            - python-yaml
            - lcov
            - libopencv-dev
          sources: &trusty_amdappsdk_sources
            - ubuntu-toolchain-r-test
      env:
        - OPENCL_LIB=amdappsdk
        - OPENCL_HEADERS_VER="22"
        - AMDAPPSDK_VERSION=291 # OpenCL 1.2
        - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=102"
        - ENV_CMAKE_OPTIONS="-DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"
    # GCC
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          packages: *trusty_amdappsdk_packages
          sources: *trusty_amdappsdk_sources
      env:
        - OPENCL_LIB=amdappsdk
        - OPENCL_HEADERS_VER="22"
        - AMDAPPSDK_VERSION=291 # OpenCL 1.2
        - ENV_CXX_FLAGS="-Wno-unused-local-typedef -DBOOST_COMPUTE_MAX_CL_VERSION=102"
        - ENV_CMAKE_OPTIONS="-DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include"
    # Trusty, AMD APP SDK v3.0.0, OpenCL 2.0
    # CLANG
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      cache:
        ccache: true
        directories:
          - ${DEPS_DIR}/boost
      addons:
       apt:
         packages: &trusty_amdappsdk_latest_boost_packages
           - g++-5
           # Misc
           - python-yaml
           - lcov
           - libopencv-dev
         sources: &trusty_amdappsdk_latest_boost_sources
           - ubuntu-toolchain-r-test
      env:
        - OPENCL_LIB=amdappsdk
        - OPENCL_HEADERS_VER="22"
        - AMDAPPSDK_VERSION=300 # OpenCL 2.0
        - BOOST_VERSION="1_65_1" # Boost 1.65.1
        - BOOST_URL="https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz"
        - ENV_CXX_FLAGS="-DBOOST_COMPUTE_MAX_CL_VERSION=200"
        - ENV_CMAKE_OPTIONS="-DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include -DBOOST_COMPUTE_USE_CPP11=ON"
    # GCC
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      cache:
        ccache: true
        directories:
          - ${DEPS_DIR}/boost
      addons:
        apt:
          packages: *trusty_amdappsdk_latest_boost_packages
          sources: *trusty_amdappsdk_latest_boost_sources
      env:
        - GCC_VERSION=5
        - OPENCL_LIB=amdappsdk
        - OPENCL_HEADERS_VER="22"
        - AMDAPPSDK_VERSION=300  # OpenCL 2.0
        - BOOST_VERSION="1_65_1" # Boost 1.65.1
        - BOOST_URL="https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz"
        - ENV_CXX_FLAGS="-DBOOST_COMPUTE_MAX_CL_VERSION=200"
        - ENV_CMAKE_OPTIONS="-DOpenCL_INCLUDE_DIR=${OPENCL_ROOT}/include -DBOOST_COMPUTE_ENABLE_COVERAGE=ON -DBOOST_COMPUTE_USE_CPP11=ON"
        - COVERAGE=true

    ############################################################################
    # OSX
    ############################################################################

    # OSX build
    - os: osx
      compiler: clang
      env:
        - ENV_CXX_FLAGS="-Wno-c99-extensions"
        - ENV_CMAKE_OPTIONS="-DBOOST_COMPUTE_HAVE_OPENCV=OFF"

cache:
  directories:
    - ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}
    - ${POCL_ROOT}

before_install:
    # Install dependencies
    - |
      # POCL dependencies for Trusty
      if [[ ${LINUX_DIST} == "trusty" && ${OPENCL_LIB} == "pocl" ]]; then
        if [ -z "$(ls -A ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION})" ]; then
          POCL_LLVM_URL=http://llvm.org/releases/${POCL_LLVM_VERSION}/clang+llvm-${POCL_LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz
          mkdir -p ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION}
          travis_retry wget --no-check-certificate --quiet -O llvm-${POCL_LLVM_VERSION}.tar.xz ${POCL_LLVM_URL}
          tar xf llvm-${POCL_LLVM_VERSION}.tar.xz -C ${DEPS_DIR}/llvm-${POCL_LLVM_VERSION} --strip-components 1
        else
          echo 'Using cached LLVM.'
        fi
      # OSX
      elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
        brew update
        /usr/bin/yes | pip uninstall numpy
        brew outdated boost || brew upgrade boost
        brew outdated cmake || brew upgrade cmake
        brew install lcov # homebrew/science/opencv
      fi
    - gem install coveralls-lcov
    - ${CXX} --version
    - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
    - ${CXX} --version

    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL=${CMAKE_URL}
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

    # Download and install Boost
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" && ${BOOST_VERSION} != "default" ]]; then
        if [ ! -f "${DEPS_DIR}/boost/${BOOST_VERSION}_cached" ]; then
          # create dirs for source and install
          mkdir -p ${DEPS_DIR}/boost${BOOST_VERSION}
          mkdir -p ${DEPS_DIR}/boost
          rm -rf ${DEPS_DIR}/boost/*
          # download
          travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/boost${BOOST_VERSION}
          pushd ${DEPS_DIR}/boost${BOOST_VERSION}
          # configure and install
          if [ "$CXX" = "g++-${GCC_VERSION}" ]; then echo "using gcc : ${GCC_VERSION} : g++-${GCC_VERSION} ;" > $HOME/user-config.jam; fi
          ./bootstrap.sh --prefix=${DEPS_DIR}/boost/ --with-libraries=program_options,filesystem,system,thread,test,timer,chrono
          ./b2 -d0 install
          popd
          rm -rf ${DEPS_DIR}/boost/include/boost/{compute,compute.hpp}
          touch ${DEPS_DIR}/boost/${BOOST_VERSION}_cached
        else
          echo 'Using cached Boost ${BOOST_VERSION} libraries.'
        fi
        export CMAKE_OPTIONS=${CMAKE_OPTIONS}" -DBOOST_ROOT=${DEPS_DIR}/boost"
      fi

    ############################################################################
    # Download OpenCL headers (and cl.hpp)
    ############################################################################
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        mkdir -p ${OPENCL_ROOT}/include/CL
        pushd ${OPENCL_ROOT}/include/CL
        travis_retry git clone --depth 1 https://github.com/KhronosGroup/OpenCL-Headers.git
        mv ./OpenCL-Headers/opencl${OPENCL_HEADERS_VER}/CL/* .
        travis_retry wget -w 1 -np -nd -nv -A h,hpp --no-check-certificate ${OPENCL_REGISTRY}/api/2.1/cl.hpp;
        popd
      fi

    ############################################################################
    # Build and install POCL https://github.com/pocl/pocl
    ############################################################################
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" && ${OPENCL_LIB} == "pocl" ]]; then
        if [ -z "$(ls -A ${POCL_ROOT}/)" ]; then
          travis_retry git clone --depth 1 https://github.com/pocl/pocl.git -b ${POCL_BRANCH}
          cd pocl
          mkdir build
          cd build
          cmake -DDIRECT_LINKAGE=ON -DENABLE_ICD=OFF -DCMAKE_C_COMPILER=${POCL_C_COMPILER} -DCMAKE_CXX_COMPILER=${POCL_CXX_COMPILER} -DWITH_LLVM_CONFIG=${POCL_LLVM_CONFIG} -DCMAKE_INSTALL_PREFIX=${POCL_ROOT}/ ..
          make install
          cd ../..
        else
          echo 'Using cached POCL lib.'
        fi
      fi

    ############################################################################
    # fglrx does not work: https://github.com/travis-ci/travis-ci/issues/5221,
    # so we build our own linkable .so file.
    # Thanks to clSPARSE for providing opencl-icd build script.
    ############################################################################
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" && ${OPENCL_LIB} == "khronos-icd" ]]; then
        mkdir -p ${OPENCL_ROOT}
        pushd ${OPENCL_ROOT}
        travis_retry git clone --depth 1 https://github.com/KhronosGroup/OpenCL-ICD-Loader.git
        mv ./OpenCL-ICD-Loader/* .
        mkdir -p inc/CL
        pushd inc/CL
        travis_retry git clone --depth 1 https://github.com/KhronosGroup/OpenCL-Headers.git
        mv ./OpenCL-Headers/opencl${OPENCL_HEADERS_VER}/CL/* .
        popd
        mkdir -p lib
        pushd lib
        cmake -G "Unix Makefiles" ..
        make
        cp ./bin/libOpenCL.so .
        popd
        popd
      fi

    ############################################################################
    # Install AMD APP SDK
    # Thanks to JuliaGPU https://github.com/JuliaGPU/OpenCL.jl
    ############################################################################
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" && ${OPENCL_LIB} == "amdappsdk" ]]; then
        mkdir -p ${OPENCL_ROOT}
        bash .travis/amd_sdk.sh ${AMDAPPSDK_VERSION}
        tar -xjf AMD-SDK.tar.bz2
        export OPENCL_VENDOR_PATH=${AMDAPPSDKROOT}/etc/OpenCL/vendors
        mkdir -p ${OPENCL_VENDOR_PATH}
        sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDKROOT}
        echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd
        if [[ ${AMDAPPSDK_VERSION} == "300" ]]; then
          export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64/sdk:${LD_LIBRARY_PATH}
          export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64/sdk
          cp ${AMDAPPSDKROOT}/lib/x86_64/libamdocl12cl64.so ${AMDAPPSDKROOT}/lib/x86_64/sdk/libamdocl12cl64.so
        # 291
        else
          export LD_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64:${LD_LIBRARY_PATH}
          export CMAKE_LIBRARY_PATH=${AMDAPPSDKROOT}/lib/x86_64
        fi
        chmod +x ${AMDAPPSDKROOT}/bin/x86_64/clinfo
        ${AMDAPPSDKROOT}/bin/x86_64/clinfo
      fi

script:
    ############################################################################
    # Build Boost.Compute tests, benchmarks and examples
    ############################################################################
    - mkdir -p build
    - cd build
    - echo ${CMAKE_OPTIONS}
    - echo ${CXX_FLAGS}
    - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" ..
    - make -j4
    - |
      if [[ ${RUN_TESTS} == "true" ]]; then
        # print OpenCL devices
        ./example/list_devices
        # run tests and examples
        ctest --output-on-failure --repeat-until-fail 2
      fi

after_success:
    - |
      if [[ ${COVERAGE} == "true" ]]; then
        lcov --directory test --base-directory ../include/boost/compute/ --capture --output-file coverage.info
        lcov --remove coverage.info '/usr*' '*/test/*' '*/deps/*' -o coverage.info
        cd .. && coveralls-lcov build/coverage.info
      fi
